### ISSUE TITLE
Buster support

### ISSUE THREAD

**Issue by ykhrustalev** [puppetlabs/puppetlabs-release#192]
I am not entirely sure this is the right place but debian buster has been released, would be great to see packages built for it specifically under https://apt.puppetlabs.com.

Thank you.

**Comment by phaer** [comment]
I think the right place would be their Jira: https://tickets.puppetlabs.com/browse/PA-2410?jql=text%20~%20%22buster%22

puppet-agent packages seem to be available now (https://github.com/puppetlabs/puppetlabs-release/pull/196), puppet-server packages seem to be blocked by https://tickets.puppetlabs.com/browse/SERVER-2423

**Comment by ykhrustalev** [comment]
thanks, resolved then
