### ISSUE TITLE
Add Fedora 32 repo

### ISSUE THREAD

**Issue by r3pek** [puppetlabs/puppetlabs-release#210]
## Use Case
Use Fedora 32

## Describe the Solution You Would Like
Repository for fedora 32

## Describe Alternatives You've Considered
Using the fedora 31 repo? don't know if it works....

**Comment by DavidRedstone** [comment]
+1

Where are the repos for F31 and F32? For Ubuntu 18.10, 19.04, 19.10, 20.04?

I also opened a feature request issue in he PDK planning repo
https://github.com/puppetlabs/pdk-planning/issues/73
