### ISSUE TITLE
Add Fedora 34 support/repo

### ISSUE THREAD

**Issue by devinmatte** [puppetlabs/puppetlabs-release#231]
## Use Case
Would like to use puppet agent on Fedora 34 using a Fedora 34 repo

## Describe the Solution You Would Like
Add a fedora 34 repo to http://yum.puppetlabs.com/puppet/fedora/

## Describe Alternatives You've Considered
Using http://yum.puppetlabs.com/puppet/fedora/32 in the meantime, which is constantly swapped back to 34 on each puppet run and requires manual intervention to update the package

## Additional Context
There also is a missing Fedora 33 repo #215 , which has made this an issue for almost a year now

**Comment by jby** [comment]
Don't hold your breath...
We seem to be considered troublemakers, if not trolls, asking for support of newer Fedora releases...

**Comment by GabrielNagy** [comment]
Hi,

Fedora 34 repos were merged in https://github.com/puppetlabs/puppetlabs-release/pull/233. Nightly builds are now installable through the repos at http://nightlies.puppet.com/yum/. Regular release packages will also be available in the next set of puppet releases (6.23.0 and 7.8.0).

Please note that there are lots of moving parts when we add support for a new platform, and this repo is just a small part of the work that needs to be done (think of it as the cherry on top after 99% of the work is completed), so we don't monitor it very closely.

A better place to submit new platform requests is our [Puppet Idea Board](https://puppet.com/puppet-idea-portal/), on the **Puppet Core** tab.

Issues regarding the general wellbeing of the repo itself (e.g. something is broken) should be directed to the [CPR](https://tickets.puppetlabs.com/projects/CPR/issues/CPR-761?filter=allopenissues) project on our JIRA.
