### ISSUE TITLE
Adding Fedora 35 and 36 Repos

### ISSUE THREAD

**Issue by devinmatte** [puppetlabs/puppetlabs-release#255]
## Use Case
Would like to use puppet agent on Fedora 36 using a Fedora 36 repo

## Describe the Solution You Would Like
Add a fedora 36 repo to http://yum.puppetlabs.com/puppet/fedora/

## Describe Alternatives You've Considered
Using http://yum.puppetlabs.com/puppet/fedora/34 in the meantime, which is constantly swapped back to 36 on each puppet run and requires manual intervention to update the package

## Additional Context
There also is a missing Fedora 35 repo , which has made this an issue for a while.
I created #231 a while ago, and have also made an idea on the [idea board](https://puppet.com/puppet-idea-portal/)

**Comment by chhex** [comment]
Hi @devinmatte  I am having i think the same problem......  running for examle 

`bolt task run puppet_agent::install`

I get : 

```
The task failed with exit code 1
  15:53:14 +0200 INFO: Version parameter not defined and no agent detected. Assuming latest.
  15:53:14 +0200 INFO: Downloading Puppet latest for Fedora...
  15:53:14 +0200 INFO: Fedora platform! Lets get the RPM...
  15:53:14 +0200 INFO: Downloading http://yum.puppet.com/puppet-release-fedora-35.noarch.rpm
  15:53:14 +0200 INFO:   to file /tmp/install.sh.2677.60222/puppet-release-fedora-35.noarch.rpm
  15:53:14 +0200 INFO: Trying wget...
  15:53:14 +0200 INFO: Retrying... [1/5]
  15:53:15 +0200 INFO: Return code: 8
  15:53:16 +0200 INFO: Retrying... [2/5]
  15:53:16 +0200 INFO: Return code: 8
  15:53:17 +0200 INFO: Retrying... [3/5]
  15:53:17 +0200 INFO: Return code: 8
  15:53:18 +0200 INFO: Retrying... [4/5]
  15:53:18 +0200 INFO: Return code: 8
  15:53:19 +0200 INFO: Retrying... [5/5]
  15:53:19 +0200 INFO: Return code: 8
  15:53:20 +0200 INFO: Trying curl...
  15:53:20 +0200 CRIT: ERROR 404
  15:53:20 +0200 CRIT: Unable to retrieve a valid package!
```

I tried to specify the version parameter : 

`bolt task run puppet_agent::install version=34`

no help: 

```
15:56:25 +0200 INFO: Version parameter defined: 34
  15:56:25 +0200 INFO: Downloading Puppet 34 for Fedora...
  15:56:25 +0200 INFO: Fedora platform! Lets get the RPM...
  15:56:25 +0200 INFO: Downloading http://yum.puppet.com/puppet-release-fedora-35.noarch.rpm
```

It sticks with the 35 Version 

You mention an alternative.... how do you actually do that?

**Comment by devinmatte** [comment]
I've just been manually editing `/etc/yum.repos.d/pc_repo` and updating the version number manually before every `yum update` on my system.
It's really not ideal.

**Comment by chhex** [comment]
That could work for me , since i am running Fedora locally in a VM for testing .... 
/etc/yum.repos.d/pc_repo on the the target , right?  Specifically for the puppet-release-fedora rpm? 
But since i am a novice , i am not quite sure the content would be ...
Great thanks for your help...

**Comment by e-gris** [comment]
Fedora 36 was added but Fedora 35 was never supported
