### ISSUE TITLE
Fedora 37 Beta is out; please get ahead of the release!

### ISSUE THREAD

**Issue by abotelho-cbn** [puppetlabs/puppetlabs-release#267]
Hi all,
It would be great if Puppet Agent for Fedora 37 was packaged and ready to go before the 37 Stable release.

See: https://docs.fedoraproject.org/en-US/releases/f37/

Target for the Stable release is October 18th: https://fedorapeople.org/groups/schedule/f-37/f-37-key-tasks.html

**Comment by joshcooper** [comment]
@abotelho-cbn Fedora releases too frequently for us to support every version. We will have Fedora 36 packages available soon and will look at adding Fedora 38 when it's ready.

**Comment by abotelho-cbn** [comment]
Would you consider at least starting support for Fedora 38 once its Beta hits? Having Puppet release months after Stable release really detracts from its value.
