### ISSUE TITLE
apt.repos.puppet.com has an invalid certificate.

### ISSUE THREAD

**Issue by atoulme** [puppetlabs/puppetlabs-release#271]
## Describe the Bug
Visit https://apt.repos.puppet.com/puppet6/index.html. The certificate is expired.

<img width="538" alt="Screen Shot 2022-11-18 at 3 08 17 PM" src="https://user-images.githubusercontent.com/16758/202818846-a46b50c7-acea-43e9-bea8-1cdafd64fd8e.png">

## Expected Behavior
The certificate should be valid.

## Steps to Reproduce
1. Go to https://ssllabs.com and enter the host name

See this result
<img width="962" alt="Screen Shot 2022-11-18 at 3 10 49 PM" src="https://user-images.githubusercontent.com/16758/202818823-ac7c15a9-2244-42c1-af30-7b6518c6e494.png">

## Environment
N/A

## Additional Context
N/A

**Comment by e-gris** [comment]
The error here was pointing production work at apt.repos.puppet.com, which is currently experimental. This has been remedied.
