### ISSUE TITLE
Debian | Puppet 7 Repo configured, but puppetserver 8 gets installed

### ISSUE THREAD

**Issue by MS-PLrlp** [puppetlabs/puppetlabs-release#291]
## Describe the Bug
We have configured puppet 7 apt repositories for Debian Bullseye, but since April 26 puppetserver 8.0.0-1bullseye gets installed via apt upgrade

## Expected Behavior
Only packages with major version 7 should be installed

## Steps to Reproduce
1. Configure puppet 7 apt repositories via puppet7-release on Debian Bullseye
2. Install puppetserver or upgrade

## Environment
 - Debian Bullseye 11.6
 - puppet7-release

**Comment by e-gris** [comment]
Fixed
