### ISSUE TITLE
Improvement request: Remove annoyance in Debian for non-updates of pkg puppet7-release

### ISSUE THREAD

**Issue by elofu17** [puppetlabs/puppetlabs-release#301]
Every now and then (a few times per year), the package `puppet7-release` is updated for no good reason.
There is no actual change, yet a new version of the package is created.
The only thing that changes is the timestamp in the changelog.gz (and the version of the package).

This is annoying.

Have I missed something? If not, could you please stop this behavior? :-)
Also, when there are actual changes, please note what changes were done in the changelog.gz file - that's what it is for. :-)

Before upgrade:
```
# zmore /usr/share/doc/puppet7-release/changelog.gz
puppet7-release (7.0.0-14bullseye) ; urgency=medium

  * Package created with FPM.

 -- Puppet, Inc. <release@puppet.com>  Wed, 17 May 2023 17:47:08 +0000

# cat puppet7-release.md5sums
79a29bccbc236e52a337843d1f8744f5  etc/apt/sources.list.d/puppet7-release.list
942cc11e9b7f1fe22064c53b70f6c5a4  etc/apt/trusted.gpg.d/puppet7-keyring.gpg
64051a99f7cce3a04f4e0dbb753d21e5  usr/share/doc/puppet7-release/changelog.gz
```
Upgrade:
```
# apt update && apt full-upgrade
The following packages will be upgraded:
  puppet7-release
Preparing to unpack .../puppet7-release_7.0.0-15bullseye_all.deb ...
Unpacking puppet7-release (7.0.0-15bullseye) over (7.0.0-14bullseye) ...
Setting up puppet7-release (7.0.0-15bullseye) ...
```
After upgrade:
```
# zmore /usr/share/doc/puppet7-release/changelog.gz
puppet7-release (7.0.0-15bullseye) ; urgency=medium

  * Package created with FPM.

 -- Puppet, Inc. <release@puppet.com>  Tue, 05 Dec 2023 11:17:21 +0000

# cat puppet7-release.md5sums
79a29bccbc236e52a337843d1f8744f5  etc/apt/sources.list.d/puppet7-release.list
942cc11e9b7f1fe22064c53b70f6c5a4  etc/apt/trusted.gpg.d/puppet7-keyring.gpg
df5e35f6e4a507ea44357b4f1aa22aa1  usr/share/doc/puppet7-release/changelog.gz
```

I know this is a minor issue, but it is annoying when, for example, monitoring tools and dashboards say there are pending packages to be installed on the fleet of Debian servers, when the change is de-facto nothing at all.

**Comment by e-gris** [comment]
I acknowledge this issue.

Unfortunately, the malfunction that causes this behavior is not easy to repair. I'm going to close this with the assurance that it won't be ignored should the opportunity arise. However, to be perfectly honest, I do not anticipate that opportunity any time soon.
