### ISSUE TITLE
Adding Fedora 39 Repo

### ISSUE THREAD

**Issue by Mstrodl** [puppetlabs/puppetlabs-release#304]
## Use Case
Would like to use puppet agent on Fedora 39 using a Fedora 39 repo

## Describe the Solution You Would Like
Add a fedora 39 repo to http://yum.puppetlabs.com/puppet/fedora/

## Describe Alternatives You've Considered
Using http://yum.puppetlabs.com/puppet/fedora/36 in the meantime, which is constantly swapped back to 39 on each puppet run and requires manual intervention to update the package

## Additional Context
See also #255 and #231

**Comment by e-gris** [comment]
We have no plans for Fedora 39. Fedora 40 was added in May 2024.
